

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    // absolute: "", 
    default: "Next Js Learn", // default title for all pages
    template: "%s | Next JS"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header
            style={{
              backgroundColor: "lightblue",
              padding: "1rem",
              color: "black",
            }}
          >
            <p>Header</p>
          </header>
          {children}
          <footer>
            <p
              style={{
                backgroundColor: "ghostwhite",
                padding: "1rem",
                color: "black",
              }}
            >
              Footer
            </p>
          </footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
